routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PageController@home');
Route::get('/home', 'PageController@home');
Route::get('/zenders', 'PageController@zenders');
Route::get('/contact', 'PageController@contact');
Route::get('liedjes/search', 'LiedController@search')->name('liedjes.search');
Route::resource('zenders', 'ZenderController');
Route::resource('programmas', 'ProgrammaController');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/liedjes', 'PageController@liedjes');
    Route::resource('liedjes', 'LiedController');

});

Auth::routes();

app/Zenders.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Zenders extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'id', 'title', 'description', 'slug'
    ];

    public function programmas()
    {
        return $this->hasMany('App\Programmas', 'zenders_id');
    }
}

app/Http/Controllers/ZenderController.php
<?php

namespace App\Http\Controllers;

use App\Programmas;
use App\Zenders;
use Illuminate\Http\Request;
use Illuminate\Support\Str;


class ZenderController extends Controller
{

    public function index()
    {
        $zenders = Zenders::orderBy('title')->paginate(env('APP_PAGINATION_LIMIT', 5));
        return view('zenders.index', compact('zenders'));
    }

    public function store(Request $request)
    {
        //Data Valideren en opvragen van de form
        $this->validate(
            $request, [
            'titel' => 'required|min:1|unique:zenders,title,NULL,id,deleted_at,NULL',
            'omschrijving' => 'required'
        ]);

        //Aangeven waar de data moet worden opgeslagen in de database
        $zenders = Zenders::create([
            'title' => $request->titel,
            'description' => $request->omschrijving,
            'slug' => Str::slug($request->titel),
        ]);

        //Data opslaan in database
        $zenders->save();

        return redirect()->route('zenders.index', $zenders->slug)->with('success', 'Zender aangemaakt');

    }

    public function show($id)
    {
        // Zet de slug variable als url
        $slug = strtolower($id);
        $programmas = Programmas::all();
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }
        return view('zenders.show', compact('zenders', 'programmas'));

    }

    public function edit($id)
    {
        // Zet de slug variable als url
        $slug = strtolower($id);
        $zenders= Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }
        return view('zenders.edit', compact('zenders'));

    }

    public function update(Request $request, $id)
    {
        //Data Valideren en opvragen van de form
        $this->validate(
            $request, [
            'titel' => 'required|min:1|unique:zenders,title,NULL,id,deleted_at,NULL'. $id,
            'omschrijving' => 'required'
        ]);

        $slug = strtolower($id);
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }

        //Aangeven waar de data moet worden opgeslagen in de database
        $zenders->title = $request->titel;
        $zenders->description = $request->omschrijving;
        $zenders->slug = Str::slug($request->titel, '-');

        //Data opslaan in database
        $zenders->save();

        return redirect()->route('zenders.index')->with('success', 'Zender bewerkt');
    }

    public function destroy($id)
    {
        // Zet de slug variable als url
        $id = strtolower($id);
        $zenders = Zenders::where('id', '=', $id)->get()->first();
        if (!$zenders) {
            abort(404);
        }

        $response = "Je hebt  $zenders->title} verwijderd";
        $zenders->delete();

        return redirect()->route('zenders.index')->with('deleted', $response);
    }
}

resources/views/zenders/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form id="save_post" method="POST" action="{{route('zenders.update', $zenders->slug)}}">
            @csrf
            @method('PATCh')
            <div class="columns has-margin-top-30">
                <label for="name"><h2>Zender toevoegen</h2></label>
            </div>

            <div class="columns has-margin-top-30">
                <input type="text" id="title" class="input is-fullwidth" name="titel" placeholder="Titel"
                       value="{{ $zenders->title }}">
            </div>

            <div class="columns has-margin-top-30">
                <input type="text" id="title" class="input is-fullwidth" name="omschrijving" placeholder="Omschrijving"
                       value="{{ $zenders->description }}">
            </div>

            <div class="columns has-margin-top-30">
                <input type="submit" class="button is-success" value="Verstuur">
            </div>

        </form>
    </div>
@endsection

resources/views/zenders/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (Auth::guest())
@else
        <form id="save_post" method="POST" action="{{route('zenders.store')}}">
            @csrf

            <div class="columns has-margin-top-30">
                <label for="name"><h2>Zender toevoegen</h2></label>
            </div>

            <div class="columns has-margin-top-30">
                <input type="text" id="title" class="input is-fullwidth" name="titel" placeholder="Titel"
                       value="{{ old('titel') }}">
            </div>

            <div class="columns has-margin-top-30">
                <input type="text" id="title" class="input is-fullwidth" name="omschrijving" placeholder="Omschrijving"
                       value="{{ old('omschrijving') }}">
            </div>

            <div class="columns has-margin-top-30">
                <input type="submit" class="button is-success" value="Verstuur">
            </div>

        </form>
        @endif
        <div class="columns has-margin-top-50">
            @forelse($zenders as $key => $data)
                @if($loop->index >= 2 && $loop->index % 3 == 0)</div>
        <div class="columns">@endif
            <div class="column is-one-third">
                <div class="card">

                    <div class="card-content">
                        <div class="content">
                            {{ substr(strip_tags($data->title), 0,120) }}{{ strlen(strip_tags($data->title)) >120 ? "..." : "" }}
                        </div>
                    </div>
                    @if (Auth::guest())
                        <footer class="card-footer">
                            <a href="{{route('zenders.show', $data->slug)}}" class="card-footer-item button is-info">Programmaoverzicht</a>
                        </footer>
                    @else
                        <footer class="card-footer">
                            <a href="{{route('zenders.show', $data->slug)}}" class="card-footer-item button is-info">Programmaoverzicht</a>
                        </footer>
                        <footer class="card-footer">
                            <a href="{{route('zenders.edit', $data->slug)}}" class="card-footer-item button is-warning">Wijzig</a>
                            <a class="card-footer-item button is-danger"
                               href="{{ route('zenders.destroy', $data->id) }}"
                               onclick="confirm('Weet je zeker dat je dit wil verwijderen?') && saveAndSubmit(event.preventDefault(),
                                   document.getElementById('delete-form-{{$data->id}}').submit())">Verwijderen</a>
                            <script>
                                function saveAndSubmit(event) {
                                    alert('De zender is verwijderd');
                                }
                            </script>

                            <form id="delete-form-{{$data->id}}" action="{{ route('zenders.destroy', $data->id) }}"
                                  method="POST"
                                  style="display: none;">
                                @csrf
                                @method('DELETE')
                            </form>
                        </footer>
                    @endif
                </div>
            </div>

            @empty
                <h3>Geen Zenders gevonden</h3>
            @endforelse
        </div>
    </div>

@endsection

resources/views/zenders/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">


        <table class="table is-bordered">
            <thead>
            @if (Auth::guest())
            <th>Programma</th>
            <th>Datum</th>
            <th>Tijd</th>
            <th>Duur in minuten</th>

                @else
                <th>Programma</th>
                <th>Datum</th>
                <th>Tijd</th>
                <th>Duur in minuten</th>
                <th></th>
                <th></th>
            @endif
            </thead>
            <tbody>
            @if (Auth::guest())
                @foreach($programmas as $key => $data)
                    <tr>
                        <th><p>{{$data->title}}</p></th>
                        <th><p>21-2</p></th>
                        <th><p>10:00 - 12:00</p></th>
                        <th><p>120</p></th>
                    </tr>
                @endforeach
            @else
                @foreach($programmas as $key => $data)
                    <tr>
                        <th><p>{{$data->title}}</p></th>
                        <th><p>21-2</p></th>
                        <th><p>10:00 - 12:00</p></th>
                        <th><p>120</p></th>
                        <th><a class="card-footer-item button is-warning">Wijzig</a></th>
                        <th><a class="card-footer-item button is-danger">Verwijder</a></th>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
    </div>
@endsection